server:
  port: 8080
  servlet:
    context-path: /api/
spring:
  application:
    name: tms-serve
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tms-serve
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
          batch-size: 100
          generate_statistics: true
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  ## quartz config
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: tms-quartz-app
            instanceId: AUTO
          threadPool:
            threadCount: 20
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            misfireThreshold: 6000
            tablePrefix: qrtz_
            isClustered: false
          plugin:
            shutdownHook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: true
  mvc:
    throw-exception-if-no-handler-found: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: haidvph05438@fpt.edu.vn
    password: ${PASS_EMAIL}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
    send-from: doanhai8080@gmail.com
logging:
  config: "classpath:log4j2-spring.xml"
storage-service:
  bucket-name: smartshoes
  img-storage-name: img
  files-storage-name: files
  base-url: https://${storage-service.bucket-name}.s3-${cloud.aws.region.static}.amazonaws.com
auth:
  token:
    admin:
      access-expire: 99999999
      refresh-expire: 99999999
    customer:
      access-expire: 99999999
      refresh-expire: 99999999
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-1